### ISSUE TITLE
Little code suggestions

### ISSUE THREAD

**Issue by vorner** [lostutils/groupby#1]
Hello

I find this little program will be useful for many things I do (I usually do something like that with combination of sed, sort, …). I also looked into the code. Do I guess right that you're still learning Rust? Could I provide few little tips?

* I glimpsed at least one unwrap that can be triggered by the user input (giving a too large group ID), which will result in ugly error message instead of nice useful one.
* Do you choose `BTreeMap`/`BTreeSet` for some specific reason? Is it the order of elements? If not, `HashMap` and `HashSet` are likely to be faster.
* Both variants (unique vs all) look very similar and differ only in the inner data type and the method used to `push`/`insert`. I think this could be done with just one piece of code that is generic over the type, and adding your own trait that implements the adding for either. Would you like me to show you such code?

**Comment by tmr232** [comment]
Hi,

Yes, I am still learning Rust. I feel like a total noob at the moment.

As for using the `BTree` variants instead of the `Hash` ones, I did that to preserve order. I am not yet sure if that is a desired feature or not.

As for your other suggestions, yes, I would be happy to see such code and learn from it :)

Thanks!

p.s.
I am happy to hear my small utility is helping others.

**Comment by tmr232** [comment]
PR merged, but I am keeping this open until I fix the error handling for user input.

**Comment by tmr232** [comment]
I improved error handling here - abfc6819c81948f3ed6b01c5937cfec3be36b8c7
Do you have any more suggestions?

**Comment by vorner** [comment]
I commented a bit on the new code (very minor things), but in general no, the code looks quite good.
